# Links to be made for tools and scripts
links:
  acc-models-lhc: ../../../../hllhc14
  errors: ../../../../lhcerrors

# Optics file
optics_file: acc-models-lhc/round/opt_round_150_1500_thin.madx

# Beam parameters
beam_config:
  lhcb1:
    beam_energy_tot: 7000           # [GeV]
  lhcb2:
    beam_energy_tot: 7000           # [GeV]

# Enable machine imperfections
enable_imperfections: false

# Enable knob synthesis (for coupling correction, if no imperfections)
enable_knob_synthesis: true

# Optics version, for choice of correction algorithms
# (ver_lhc_run or ver_hllhc_optics)
ver_hllhc_optics: 1.4
ver_lhc_run: null

# Parameters for machine imperfections
pars_for_imperfections:
  par_myseed: 1
  par_correct_for_D2: 0
  par_correct_for_MCBX: 0
  par_on_errors_LHC: 1
  par_off_errors_Q4_inIP15: 0
  par_off_errors_Q5_inIP15: 0
  par_on_errors_MBH: 1
  par_on_errors_Q4: 1
  par_on_errors_D2: 1
  par_on_errors_D1: 1
  par_on_errors_IT: 1
  par_on_errors_MCBRD: 0
  par_on_errors_MCBXF: 0
  par_on_errors_NLC: 0
  par_write_errortable: 1
